import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import axios from 'axios'


export default function Home() {

  const [title, setTitle] = useState("");

  const handleAddPost =async (e)=>{
    e.preventDefault();

    try{
      const res = await fetch('http://localhost:8000/api/blog/create', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ title })
      })
      .then(response => response.json())
      .then(data => {
            if (!data) {
                console.log('No Data found')
            }
            console.log('added')
            console.log(data)
            console.log(data.content)
        });
      }
      catch(e){
          console.log(e);
          console.log('something went wrong');
      }



  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
                  <form onSubmit={handleAddPost}>
                    {/* Email Address */}
                    <div>
                        <input
                            type="text"
                            className="block mt-1 w-full"
                            value = {title}
                            onChange={event => setTitle(event.target.value)}
                          
                            autoFocus
                        />
                    </div>

                    <div className="flex items-center justify-end mt-4">
                        <button type='submit' className="ml-3">Save</button>
                    </div>
                  </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
